name = "guardman-api"
main = "worker/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "guardman-d1"
database_id = "9bd733ce-2dae-4b51-b968-75f8f92e38d5"

[vars]
ENVIRONMENT = "production"

[triggers]
crons = ["0 3 * * *"]
