-- =============================================
-- GUARDMAN - Insert Initial Data
-- =============================================

-- Insert Services
INSERT OR REPLACE INTO services (id, name, slug, description, short_description, hero_heading, meta_title, meta_description, price_range, features, process, common_issues, image, featured, status, sort) VALUES
(1, 'Guardias de Seguridad', 'guardias-de-seguridad', 'Servicio de guardias de seguridad profesionales para la protección de personas, bienes y propiedades en toda la Región Metropolitana.', 'Protección profesional con guardias certificados las 24 horas', 'Servicio de Guardias de Seguridad en Santiago', 'Guardias de Seguridad en Santiago | GuardMan Chile', 'Contrata guardias de seguridad profesionales en Santiago. Personal certificado, disponible 24/7.', '$$$', '["Guardias certificados","Disponibles 24/7","Uniformados","Capacitados en emergencias"]', '[{"step":"Consulta","description":"Evaluamos necesidades"},{"step":"Propuesta","description":"Diseñamos plan"},{"step":"Implementación","description":"Iniciamos servicio"}]', '["Accesos no controlados","Robos en empresas"]', NULL, 0, 'published', 1),
(2, 'CCTV y Videovigilancia', 'cctv-videovigilancia', 'Instalación y monitoreo de sistemas de cámaras de seguridad (CCTV) de última generación.', 'Cámaras de última generación con monitoreo 24/7', 'Sistemas de CCTV y Videovigilancia', 'CCTV en Santiago | Cámaras de Seguridad | GuardMan', 'Instalación de cámaras CCTV en Santiago. Monitoreo remoto 24/7.', '$$$$', '["Cámaras IP","Acceso remoto","Monitoreo 24/7","Grabación en la nube"]', '[{"step":"Visita técnica","description":"Evaluamos áreas a vigilar"},{"step":"Instalación","description":"Implementación profesional"},{"step":"Capacitación","description":"Te enseñamos a usar el sistema"}]', '["Cámaras dañadas","Sin acceso remoto"]', NULL, 0, 'published', 2),
(3, 'Control de Accesos', 'control-de-accesos', 'Sistemas electrónicos de control de accesos para edificios y empresas.', 'Control total de accesos con tecnología biométrica', 'Control de Accesos Profesional', 'Control de Accesos Santiago | GuardMan', 'Sistemas de control de accesos. Biométrico, tarjetas RFID.', '$$$', '["Lectores RFID","Biométricos","Cerraduras electrónicas","Registro de ingresos"]', '[{"step":"Análisis","description":"Evaluamos puntos de acceso"},{"step":"Instalación","description":"Implementación por técnicos"},{"step":"Soporte","description":"Mantenimiento continuo"}]', '["Llaves perdidas","Accesos no autorizados"]', NULL, 0, 'published', 3),
(4, 'Escoltas Privados', 'escoltas-privados', 'Servicio de escolta personal para ejecutivos y celebridades.', 'Protección personalizada para executives', 'Servicio de Escoltas Privados', 'Escoltas Privados Santiago | Protección Ejecutiva | GuardMan', 'Servicio de escoltas privados en Santiago.', '$$$$', '["Evaluación de riesgo","Planificación de rutas","Escoltas bilingües","Cobertura 24/7"]', '[{"step":"Consulta confidencial","description":"Evaluamos necesidades"},{"step":"Plan de seguridad","description":"Estrategia personalizada"},{"step":"Implementación","description":"Asignamos escoltas"}]', '["Amenazas de seguridad","Riesgo por exposición"]', NULL, 0, 'published', 4),
(5, 'Monitoreo 24/7', 'monitoreo-24-7', 'Centro de operaciones con monitoreo remoto las 24 horas.', 'Centro de control con vigilancia las 24 horas', 'Monitoreo y Vigilancia las 24 Horas', 'Monitoreo 24/7 Santiago | Centro de Control | GuardMan', 'Monitoreo de cámaras y alarmas las 24 horas.', '$$$', '["Centro de control propio","Respuesta inmediata","Coordinación con Carabineros","Alertas por SMS"]', '[{"step":"Instalación","description":"Conectamos sistemas"},{"step":"Monitoreo activo","description":"Supervisión 24/7"},{"step":"Respuesta","description":"Protocolo ante alertas"}]', '["Alarmas sin respuesta","Emergencias sin coordinación"]', NULL, 0, 'published', 5),
(6, 'Seguridad para Eventos', 'seguridad-eventos', 'Servicio especializado para eventos corporativos, sociales y masivos.', 'Seguridad profesional para todo tipo de eventos', 'Seguridad para Eventos Corporativos', 'Seguridad para Eventos Santiago | GuardMan', 'Seguridad para eventos corporativos y sociales.', '$$$$', '["Planificación previa","Control de accesos","Gestión de multitudes","Coordinación con productores"]', '[{"step":"Reunión con productores","description":"Entendemos necesidades"},{"step":"Despliegue","description":"Personal en puntos estratégicos"},{"step":"Coordinación","description":"Comunicación constante"}]', '["Control de invitados","Gestión de masas","Seguridad VIP"]', NULL, 0, 'published', 6),
(7, 'Seguridad Industrial', 'seguridad-industrial', 'Protección especializada para instalaciones industriales, bodegas y obras.', 'Protección para industrias, bodegas y obras', 'Seguridad Industrial y Obras', 'Seguridad Industrial Santiago | GuardMan', 'Seguridad industrial y vigilancia perimetral.', '$$$', '["Vigilancia perimetral","Control de vehículos","Prevención de robos","Reportes de rondas"]', '[{"step":"Visita técnica","description":"Evaluamos la instalación"},{"step":"Análisis de riesgos","description":"Identificamos vulnerabilidades"},{"step":"Monitoreo","description":"Supervisión continua"}]', '["Robos en bodegas","Acceso no autorizado a obras"]', NULL, 0, 'published', 7),
(8, 'Auditoría de Seguridad', 'auditoria-seguridad', 'Evaluación profesional de las necesidades de seguridad.', 'Evaluación profesional de vulnerabilidades', 'Auditoría de Seguridad Profesional', 'Auditoría de Seguridad Santiago | GuardMan', 'Auditoría de seguridad profesional.', '$$', '["Visita técnica gratuita","Análisis de vulnerabilidades","Plan documentado","Recomendaciones"]', '[{"step":"Solicitud","description":"Contacta y agendamos"},{"step":"Visita técnica","description":"Inspeccionamos sin costo"},{"step":"Informe","description":"Análisis detallado"}]', '["No saber qué necesita","Inversión incorrecta"]', NULL, 0, 'published', 8),
(9, 'Guard Pod', 'guard-pod', 'Unidades móviles de vigilancia autónomas. Guard Pod es un módulo de seguridad prefabricado con tecnología de punta, ideal para obras, eventos temporales y zonas sin infraestructura.', 'Unidades móviles de vigilancia 24/7 con tecnología avanzada', 'Guard Pod - Vigilancia Móvil Autónoma', 'Guard Pod en Santiago | Unidad Móvil de Seguridad | GuardMan', 'Guard Pod: unidad móvil de vigilancia autónoma. Solución ideal para obras, eventos y zonas remotas sin infraestructura.', '$$$$', '["Módulo prefabricado autónomo","Energía solar con baterías de respaldo","Cámaras PTZ 360 grados","Sensor de movimiento y térmico","Conectividad 4G/LTE","Alarma sonora y luces estroboscópicas","Monitoreo remoto 24/7","Instalación en menos de 2 horas"]', '[{"step":"Solicitud","description":"Evaluamos necesidades y ubicación"},{"step":"Propuesta","description":"Diseñamos solución personalizada"},{"step":"Entrega","description":"Instalamos Guard Pod en sitio"},{"step":"Monitoreo","description":"Supervisión remota continua"}]', '["Zonas sin luz eléctrica","Eventos temporales sin infraestructura","Obras sin vigilancia permanente"]', NULL, 0, 'published', 9);

-- Insert Locations
INSERT OR REPLACE INTO locations (id, name, slug, zone, description, neighborhoods, landmarks, priority_score, latitude, longitude, meta_title, meta_description, featured, status, sort) VALUES
(1, 'Las Condes', 'las-condes', 'Oriente', 'El sector financiero más importante de Santiago, hogar de oficinas corporativas de empresas multinacionales, bancos y centros comerciales como Parque Arauco y Alto Las Condes. Alta demanda de seguridad empresarial y residencial de lujo.', '["Sanhattan","Parque Arauco","Alto Las Condes","El Golf","Apumanque"]', '["Mall Parque Arauco","Alto Las Condes","Centro Médico Las Condes"]', 10, -33.4017, -70.5783, 'Seguridad Privada en Las Condes | GuardMan Chile', 'Guardias de seguridad y CCTV en Las Condes. Protección para empresas, oficinas y residenciales premium con guardias certificados OS-10.', 1, 'published', 1),
(2, 'Vitacura', 'vitacura', 'Oriente', 'Sector de al
