/**
 * CMS Data Module - Lee contenido desde D1/CMS
 */

// Service sections cache
let serviceSectionsCache: Record<string, any> = {};

// Location sections cache  
let locationSectionsCache: Record<string, any> = {};

// Sector sections cache
let sectorSectionsCache: Record<string, any> = {};

// Images cache
let imagesCache: Record<string, any> = {};

// Load from local files (generated by export)
import { readFileSync, existsSync, readdirSync } from 'fs';

const CMS_DIR = 'src/data/cms';

/**
 * Get service sections from CMS
 */
export function getServiceSections(slug: string): any {
  // Check cache
  if (serviceSectionsCache[slug]) {
    return serviceSectionsCache[slug];
  }

  // Load from file
  const filePath = `${CMS_DIR}/${slug}.json`;
  
  if (existsSync(filePath)) {
    try {
      const data = JSON.parse(readFileSync(filePath, 'utf-8'));
      serviceSectionsCache[slug] = data.sections || {};
      return serviceSectionsCache[slug];
    } catch (e) {
      console.error(`Error loading service ${slug}:`, e);
    }
  }

  return null;
}

/**
 * Get location sections from CMS
 */
export function getLocationSections(slug: string): any {
  if (locationSectionsCache[slug]) {
    return locationSectionsCache[slug];
  }

  const filePath = `${CMS_DIR}/location-${slug}.json`;
  
  if (existsSync(filePath)) {
    try {
      const data = JSON.parse(readFileSync(filePath, 'utf-8'));
      locationSectionsCache[slug] = data.sections || {};
      return locationSectionsCache[slug];
    } catch (e) {
      console.error(`Error loading location ${slug}:`, e);
    }
  }

  return null;
}

/**
 * Get all services metadata
 */
export function getServicesList(): any[] {
  const filePath = `${CMS_DIR}/services.json`;
  
  if (existsSync(filePath)) {
    try {
      const data = JSON.parse(readFileSync(filePath, 'utf-8'));
      // D1 query returns { results: [...], meta: {...} }
      return data.results || data || [];
    } catch (e) {
      console.error('Error loading services list:', e);
    }
  }

  return [];
}

/**
 * Get all locations metadata
 */
export function getLocationsList(): any[] {
  const filePath = `${CMS_DIR}/locations.json`;
  
  if (existsSync(filePath)) {
    try {
      const data = JSON.parse(readFileSync(filePath, 'utf-8'));
      // D1 query returns { results: [...], meta: {...} }
      return data.results || data || [];
    } catch (e) {
      console.error('Error loading locations list:', e);
    }
  }

  return [];
}

/**
 * Get service by slug (metadata only)
 */
export function getService(slug: string): any {
  const sections = getServiceSections(slug);
  const servicesList = getServicesList();
  const serviceMeta = servicesList.find(s => s.slug === slug);
  
  return {
    ...serviceMeta,
    sections
  };
}

/**
 * Get location by slug (metadata only)
 */
export function getLocation(slug: string): any {
  const sections = getLocationSections(slug);
  const locationsList = getLocationsList();
  const locationMeta = locationsList.find(l => l.slug === slug);
  
  return {
    ...locationMeta,
    sections
  };
}

/**
 * Preload all services into cache
 */
export function preloadServices(): void {
  if (!existsSync(CMS_DIR)) return;
  
  const files = readdirSync(CMS_DIR);
  
  for (const file of files) {
    if (file.endsWith('.json') && !file.startsWith('location-') && file !== 'services.json' && file !== 'locations.json' && file !== 'config.json') {
      const slug = file.replace('.json', '');
      getServiceSections(slug);
    }
  }
}

/**
 * Preload all locations into cache
 */
export function preloadLocations(): void {
  if (!existsSync(CMS_DIR)) return;
  
  const files = readdirSync(CMS_DIR);
  
  for (const file of files) {
    if (file.startsWith('location-') && file.endsWith('.json')) {
      const slug = file.replace('location-', '').replace('.json', '');
      getLocationSections(slug);
    }
  }
}

// ============================================
// SECTOR SECTIONS
// ============================================

/**
 * Get sector sections from CMS
 */
export function getSectorSections(slug: string): any {
  if (sectorSectionsCache[slug]) {
    return sectorSectionsCache[slug];
  }

  const filePath = `${CMS_DIR}/sector-${slug}.json`;
  
  if (existsSync(filePath)) {
    try {
      const data = JSON.parse(readFileSync(filePath, 'utf-8'));
      sectorSectionsCache[slug] = data.sections || {};
      return sectorSectionsCache[slug];
    } catch (e) {
      console.error(`Error loading sector ${slug}:`, e);
    }
  }

  return null;
}

/**
 * Get all sectors list
 */
export function getSectorsList(): any[] {
  const filePath = `${CMS_DIR}/sectors.json`;
  
  if (existsSync(filePath)) {
    try {
      const data = JSON.parse(readFileSync(filePath, 'utf-8'));
      return data.results || data || [];
    } catch (e) {
      console.error('Error loading sectors list:', e);
    }
  }

  // Fallback: generate from files
  if (!existsSync(CMS_DIR)) return [];
  const files = readdirSync(CMS_DIR);
  
  return files
    .filter(f => f.startsWith('sector-') && f.endsWith('.json'))
    .map(f => {
      const slug = f.replace('sector-', '').replace('.json', '');
      const data = JSON.parse(readFileSync(`${CMS_DIR}/${f}`, 'utf-8'));
      return {
        slug,
        name: data.sections?.hero?.heading || slug,
        hero: data.sections?.hero || {}
      };
    });
}

/**
 * Get sector by slug
 */
export function getSector(slug: string): any {
  const sections = getSectorSections(slug);
  const sectorsList = getSectorsList();
  const sectorMeta = sectorsList.find(s => s.slug === slug);
  
  return {
    ...sectorMeta,
    sections
  };
}

/**
 * Preload all sectors into cache
 */
export function preloadSectors(): void {
  if (!existsSync(CMS_DIR)) return;
  
  const files = readdirSync(CMS_DIR);
  
  for (const file of files) {
    if (file.startsWith('sector-') && file.endsWith('.json')) {
      const slug = file.replace('sector-', '').replace('.json', '');
      getSectorSections(slug);
    }
  }
}

// ============================================
// IMAGES
// ============================================

/**
 * Get all images from CMS
 */
export function getAllImages(): any[] {
  const filePath = `${CMS_DIR}/images.json`;
  
  if (existsSync(filePath)) {
    try {
      const data = JSON.parse(readFileSync(filePath, 'utf-8'));
      return data.images || [];
    } catch (e) {
      console.error('Error loading images:', e);
    }
  }

  return [];
}

/**
 * Get images by entity type and slug
 */
export function getImages(entityType: string, entitySlug?: string): any[] {
  const allImages = getAllImages();
  
  return allImages.filter(img => {
    if (img.entity_type !== entityType) return false;
    if (entitySlug && img.entity_slug !== entitySlug) return false;
    return true;
  });
}

/**
 * Get hero image for an entity
 */
export function getHeroImage(entityType: string, entitySlug: string): any | null {
  const images = getImages(entityType, entitySlug);
  return images.find(img => img.is_hero) || null;
}

/**
 * Get featured images
 */
export function getFeaturedImages(): any[] {
  const allImages = getAllImages();
  return allImages.filter(img => img.is_featured);
}

/**
 * Get image by slug
 */
export function getImage(slug: string): any | null {
  if (imagesCache[slug]) {
    return imagesCache[slug];
  }

  const allImages = getAllImages();
  const image = allImages.find(img => img.slug === slug) || null;
  
  if (image) {
    imagesCache[slug] = image;
  }
  
  return image;
}

/**
 * Get images organized by type
 */
export function getImagesByType(): Record<string, any[]> {
  const allImages = getAllImages();
  const organized: Record<string, any[]> = {};
  
  for (const img of allImages) {
    if (!organized[img.entity_type]) {
      organized[img.entity_type] = [];
    }
    organized[img.entity_type].push(img);
  }
  
  return organized;
}
