/**
 * CMS Data Module - Lee contenido desde D1/CMS
 */

// Service sections cache
let serviceSectionsCache: Record<string, any> = {};

// Location sections cache  
let locationSectionsCache: Record<string, any> = {};

// Load from local files (generated by export)
import { readFileSync, existsSync, readdirSync } from 'fs';

const CMS_DIR = 'src/data/cms';

/**
 * Get service sections from CMS
 */
export function getServiceSections(slug: string): any {
  // Check cache
  if (serviceSectionsCache[slug]) {
    return serviceSectionsCache[slug];
  }

  // Load from file
  const filePath = `${CMS_DIR}/${slug}.json`;
  
  if (existsSync(filePath)) {
    try {
      const data = JSON.parse(readFileSync(filePath, 'utf-8'));
      serviceSectionsCache[slug] = data.sections || {};
      return serviceSectionsCache[slug];
    } catch (e) {
      console.error(`Error loading service ${slug}:`, e);
    }
  }

  return null;
}

/**
 * Get location sections from CMS
 */
export function getLocationSections(slug: string): any {
  if (locationSectionsCache[slug]) {
    return locationSectionsCache[slug];
  }

  const filePath = `${CMS_DIR}/location-${slug}.json`;
  
  if (existsSync(filePath)) {
    try {
      const data = JSON.parse(readFileSync(filePath, 'utf-8'));
      locationSectionsCache[slug] = data.sections || {};
      return locationSectionsCache[slug];
    } catch (e) {
      console.error(`Error loading location ${slug}:`, e);
    }
  }

  return null;
}

/**
 * Get all services metadata
 */
export function getServicesList(): any[] {
  const filePath = `${CMS_DIR}/services.json`;
  
  if (existsSync(filePath)) {
    try {
      const data = JSON.parse(readFileSync(filePath, 'utf-8'));
      // D1 query returns { results: [...], meta: {...} }
      return data.results || data || [];
    } catch (e) {
      console.error('Error loading services list:', e);
    }
  }

  return [];
}

/**
 * Get all locations metadata
 */
export function getLocationsList(): any[] {
  const filePath = `${CMS_DIR}/locations.json`;
  
  if (existsSync(filePath)) {
    try {
      const data = JSON.parse(readFileSync(filePath, 'utf-8'));
      // D1 query returns { results: [...], meta: {...} }
      return data.results || data || [];
    } catch (e) {
      console.error('Error loading locations list:', e);
    }
  }

  return [];
}

/**
 * Get service by slug (metadata only)
 */
export function getService(slug: string): any {
  const sections = getServiceSections(slug);
  const servicesList = getServicesList();
  const serviceMeta = servicesList.find(s => s.slug === slug);
  
  return {
    ...serviceMeta,
    sections
  };
}

/**
 * Get location by slug (metadata only)
 */
export function getLocation(slug: string): any {
  const sections = getLocationSections(slug);
  const locationsList = getLocationsList();
  const locationMeta = locationsList.find(l => l.slug === slug);
  
  return {
    ...locationMeta,
    sections
  };
}

/**
 * Preload all services into cache
 */
export function preloadServices(): void {
  if (!existsSync(CMS_DIR)) return;
  
  const files = readdirSync(CMS_DIR);
  
  for (const file of files) {
    if (file.endsWith('.json') && !file.startsWith('location-') && file !== 'services.json' && file !== 'locations.json' && file !== 'config.json') {
      const slug = file.replace('.json', '');
      getServiceSections(slug);
    }
  }
}

/**
 * Preload all locations into cache
 */
export function preloadLocations(): void {
  if (!existsSync(CMS_DIR)) return;
  
  const files = readdirSync(CMS_DIR);
  
  for (const file of files) {
    if (file.startsWith('location-') && file.endsWith('.json')) {
      const slug = file.replace('location-', '').replace('.json', '');
      getLocationSections(slug);
    }
  }
}