/**
 * GuardMan Chile — Media Map
 * Single source of truth for image paths.
 * Generated by sync-from-admin.mjs from D1 media_library + media_entities.
 * Falls back to hardcoded defaults when media-map.json is not available.
 */
import { readFileSync, existsSync } from 'fs';

interface MediaEntry { key: string; alt: string }
type MediaMap = Record<string, Record<string, Record<string, MediaEntry>>>;

const MAP_PATH = 'src/data/cms/media-map.json';

function loadMap(): MediaMap {
  if (existsSync(MAP_PATH)) {
    try {
      return JSON.parse(readFileSync(MAP_PATH, 'utf-8'));
    } catch { /* fallback */ }
  }
  return {};
}

const map = loadMap();

/** Get image path for an entity usage. Returns null if not found. */
export function getMediaImage(entityType: string, slug: string, usage: string): string | null {
  const entry = map[entityType]?.[slug]?.[usage];
  return entry ? `/${entry.key}` : null;
}

/** Get alt text for an entity usage */
export function getMediaAlt(entityType: string, slug: string, usage: string): string {
  return map[entityType]?.[slug]?.[usage]?.alt || '';
}

/** Get all images for an entity type */
export function getEntityTypeImages(entityType: string): Record<string, Record<string, MediaEntry>> {
  return map[entityType] || {};
}

// ===== Convenience helpers (replace hardcoded SERVICE_IMAGES, SECTOR_IMAGES, etc.) =====

export function getServiceHero(slug: string): string {
  return getMediaImage('service', slug, 'hero') || `/images/service-${slug}.webp`;
}

export function getSectorHero(slug: string): string {
  return getMediaImage('sector', slug, 'hero') || '/images/hero-home.webp';
}

export function getLocationHero(slug: string): string {
  return getMediaImage('location', slug, 'hero') || '/images/hero-home.webp';
}

export function getClientLogo(slug: string): string {
  return getMediaImage('client', slug, 'logo') || `/images/client-${slug}.webp`;
}

// Global images
export const GLOBAL_HERO = getMediaImage('global', 'global', 'hero') || '/images/hero-home.webp';
export const GLOBAL_OG = getMediaImage('global', 'global', 'og') || '/images/og-default.webp';
export const GLOBAL_BADGE = getMediaImage('global', 'global', 'badge') || '/images/escudo-os10.webp';
export const GLOBAL_STAFF = getMediaImage('global', 'global', 'staff') || '/images/nosotros_seccion.webp';
export const GUARDPOD_IMAGE = getMediaImage('global', 'guard-pod', 'product') || '/images/s4-thumbnail.webp';
export const AJAX_IMAGE = getMediaImage('global', 'ajax', 'partner') || '/images/Ajax-systems-header.jpg';
